const $ = id => document.getElementById(id);
const nf = new Intl.NumberFormat('pt-BR');
const money = new Intl.NumberFormat('pt-BR', {style:'currency',currency:'BRL'});
const fmtDate = s => new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC',day:'2-digit',month:'short',year:'numeric'}).format(new Date(s+'T12:00:00Z'));
const metricNames = {spend:'Investimento',impressions:'Impressões',link_clicks:'Cliques no link',landing_page_views:'Visualizações da página',conversations:'Conversas iniciadas',profile_visits:'Visitas ao perfil',purchases:'Compras atribuídas',purchase_value:'Valor de compras atribuído',lead_motor:'Cliques no motor de reserva',lead_whats:'Cliques no WhatsApp'};
const typeNames = {'reach':'Alcance (tipo exportado)','actions:omni_landing_page_view':'Visualização da página','actions:onsite_conversion.messaging_conversation_started_7d':'Conversa por mensagem','profile_visit_view':'Visita ao perfil','actions:offsite_conversion.fb_pixel_purchase':'Compra atribuída'};
const state = {data:null,rows:[],sort:'spend',desc:true};
function total(rows,key){let seen=false,n=0;for(const r of rows){if(r[key]!==null&&r[key]!==undefined){seen=true;n+=r[key]}}return seen?n:null}
function ratio(a,b){return a===null||b===null||b===0?null:a/b}
function number(v){return v===null?'—':nf.format(v)}
function currency(v){return v===null?'—':money.format(v/100)}
function metricValue(v,key){return key==='spend'?currency(v):number(v)}
function addOption(select,value,label){const opt=document.createElement('option');opt.value=value;opt.textContent=label;select.append(opt)}
function filterRows(rows,{from,to,c='',s='',a='',t=''}){return rows.filter(r=>r.d>=from&&r.d<=to&&(!c||r.c===c)&&(!s||r.s===s)&&(!a||r.a===a)&&(!t||r.t===t))}
function getFiltered(){return filterRows(state.data.rows,{from:$('from').value,to:$('to').value,c:$('campaign').value,s:$('adset').value,a:$('ad').value,t:$('type').value})}
function options(id,values,current,label){const el=$(id);el.replaceChildren();addOption(el,'',label);for(const v of values)addOption(el,v,v);if(values.includes(current))el.value=current;else el.value=''}
function refreshDependencies(){const c=$('campaign').value,s=$('adset').value;const inDates=state.data.rows.filter(r=>r.d>=$('from').value&&r.d<=$('to').value&&(!$('type').value||r.t===$('type').value));
  const cs=[...new Set(inDates.map(r=>r.c))].sort();options('campaign',cs,c,'Todas as campanhas');
  const ss=[...new Set(inDates.filter(r=>!$('campaign').value||r.c===$('campaign').value).map(r=>r.s))].sort();options('adset',ss,s,'Todos os conjuntos');
  const aa=[...new Set(inDates.filter(r=>(!$('campaign').value||r.c===$('campaign').value)&&(!$('adset').value||r.s===$('adset').value)).map(r=>r.a))].sort();options('ad',aa,$('ad').value,'Todos os anúncios')}
function card(title,value,caption,primary=false){const el=document.createElement('article');el.className='kpi'+(primary?' primary':'');const t=document.createElement('span'),v=document.createElement('strong'),s=document.createElement('small');t.textContent=title;v.textContent=value;s.textContent=caption;el.append(t,v,s);return el}
function renderKpis(rows){const spend=total(rows,'spend'),impressions=total(rows,'impressions'),clicks=total(rows,'link_clicks'),conversations=total(rows,'conversations');const cards=[
  ['Investimento',currency(spend),'Total do recorte',true],['Impressões',number(impressions),'Exibições dos anúncios'],['Cliques no link',number(clicks),'CTR: '+(ratio(clicks,impressions)===null?'—':(ratio(clicks,impressions)*100).toLocaleString('pt-BR',{maximumFractionDigits:2})+'%')],
  ['CPC do link',ratio(spend,clicks)===null?'—':currency(ratio(spend,clicks)),'Gasto ÷ cliques'],['Conversas iniciadas',number(conversations),'Evento atribuído pela Meta'],['CPM',ratio(spend,impressions)===null?'—':currency(ratio(spend,impressions)*1000),'Gasto ÷ impressões × 1.000'],
  ['Visitas ao perfil',number(total(rows,'profile_visits')),'Instagram'],['Visualizações da página',number(total(rows,'landing_page_views')),'Página de destino'],['Compras atribuídas',number(total(rows,'purchases')),'Não confirma reservas'],['Valor de compras Meta',currency(total(rows,'purchase_value')),'Não é receita realizada'],
  ['Leads: motor de reserva',number(total(rows,'lead_motor')),'Campo ausente quando —'],['Leads: WhatsApp',number(total(rows,'lead_whats')),'Campo ausente quando —']];
  $('kpis').replaceChildren(...cards.map(c=>card(...c)))}
function renderChart(rows){const key=$('metric').value,grain=$('grain').value;const groups=new Map();for(const r of rows){const bucket=grain==='month'?r.d.slice(0,7):r.d;if(!groups.has(bucket))groups.set(bucket,[]);groups.get(bucket).push(r)}
  const entries=[...groups].sort(([a],[b])=>a.localeCompare(b)).map(([day,list])=>[day,total(list,key)]);const max=Math.max(1,...entries.map(([,v])=>v||0));const chart=$('chart');chart.replaceChildren();for(const [i,[label,v]] of entries.entries()){const bar=document.createElement('div');bar.className='bar';bar.style.height=v===null?'0':Math.max(1,v/max*100)+'%';bar.title=`${label}: ${metricValue(v,key)}`;bar.tabIndex=0;bar.setAttribute('aria-label',bar.title);if(grain==='month'||entries.length<=15){const span=document.createElement('span');span.textContent=grain==='month'?label.slice(5):label.slice(5);bar.append(span)}chart.append(bar)}
  chart.setAttribute('aria-label',`${metricNames[key]} em ${entries.length} ${grain==='month'?'meses':'dias'}; ${entries.map(([d,v])=>`${d}: ${metricValue(v,key)}`).join('; ')||'sem dados'}`);
  const body=$('series-table');body.replaceChildren(...entries.map(([d,v])=>{const tr=document.createElement('tr');for(const value of [d,metricValue(v,key)]){const td=document.createElement('td');td.textContent=value;tr.append(td)}tr.lastChild.className='num';return tr}));
  $('chart-note').textContent=entries.length?`Há ${entries.length} ${grain==='month'?'meses':'dias'} com registros no recorte. Períodos sem linha no export não são preenchidos com zero.`:'Nenhum registro neste recorte.'}
function groupRows(rows,level){const key={campaign:'c',adset:'s',ad:'a'}[level],map=new Map();for(const r of rows){if(!map.has(r[key]))map.set(r[key],[]);map.get(r[key]).push(r)}return [...map].map(([label,list])=>({label,spend:total(list,'spend'),impressions:total(list,'impressions'),link_clicks:total(list,'link_clicks'),conversations:total(list,'conversations'),profile_visits:total(list,'profile_visits'),purchases:total(list,'purchases'),cpc:ratio(total(list,'spend'),total(list,'link_clicks'))}))}
function renderTable(rows){let groups=groupRows(rows,$('level').value);groups.sort((a,b)=>{const av=a[state.sort],bv=b[state.sort];let cmp=typeof av==='string'?av.localeCompare(bv):((av??-1)-(bv??-1));return (state.desc?-1:1)*cmp});const body=$('comparison-body');body.replaceChildren(...groups.map(g=>{const tr=document.createElement('tr');for(const key of ['label','spend','impressions','link_clicks','conversations','profile_visits','purchases','cpc']){const td=document.createElement('td');td.className=key==='label'?'':'num';td.textContent=key==='label'?g.label:key==='spend'||key==='cpc'?(g[key]===null?'—':currency(g[key])):number(g[key]);tr.append(td)}return tr}));$('table-note').textContent=groups.length?`${groups.length} entidades no recorte. Códigos preservam a identidade sem divulgar nomes internos. “—” indica campo ausente ou denominador zero.`:'Nenhuma entidade neste recorte. Amplie as datas ou limpe os filtros.'}
function render(){refreshDependencies();const rows=getFiltered();state.rows=rows;renderKpis(rows);renderChart(rows);renderTable(rows);$('scope').textContent=`${fmtDate($('from').value)} a ${fmtDate($('to').value)} · ${rows.length.toLocaleString('pt-BR')} linhas`;
  const active=[];for(const id of ['type','campaign','adset','ad'])if($(id).value)active.push($(id).selectedOptions[0].textContent);$('active').textContent=active.length?'Filtros ativos: '+active.join(' · '):'Todos os tipos e entidades disponíveis no período.'}
function setPreset(v){const end=state.data.period.until;let start=state.data.period.since;if(v==='30'||v==='7'){const d=new Date(end+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(Number(v)-1));start=d.toISOString().slice(0,10)}if(v==='month')start=end.slice(0,7)+'-01';$('from').value=start;$('to').value=end;render()}
async function main(){try{const response=await fetch('data.json',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);state.data=await response.json();const d=state.data;
  $('version').textContent='v '+d.build_id;$('latest').textContent=fmtDate(d.period.until);$('source-window').textContent=`Histórico: ${fmtDate(d.period.since)} a ${fmtDate(d.period.until)}`;
  $('from').min=$('to').min=d.period.since;$('from').max=$('to').max=d.period.until;
  const types=[...new Set(d.rows.map(r=>r.t).filter(Boolean))].sort();for(const t of types)addOption($('type'),t,typeNames[t]||`Tipo: ${t}`);
  $('coverage').textContent=`O arquivo diário validado contém ${nf.format(d.coverage.daily_rows)} linhas, ${d.coverage.campaigns} campanhas, ${d.coverage.adsets} conjuntos e ${d.coverage.ads} anúncios. A interface Meta mostrava ${d.coverage.ui_campaigns_observed} campanhas e ${d.coverage.ui_ads_observed} anúncios; a exportação adicional incluindo excluídas contém ${d.coverage.inventory_campaigns_exported} campanhas. A diferença cadastral segue sem reconciliação completa e não mede gasto ausente.`;
  const attributions=[...new Set(d.rows.map(r=>r.at).filter(Boolean))];
  const provenance=[['Fonte','Exportação Meta Ads, anúncio por dia'],['Última data incluída',fmtDate(d.period.until)],['Exportado em',d.source_export_time||'Horário não informado pelo arquivo'],['Importado em',new Date(d.import_time).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})],['Atribuição',`${attributions.length} configurações distintas no export; conjunto misto`],['Hash dos dados',d.data_hash]];
  $('provenance').replaceChildren(...provenance.flatMap(([k,v])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;return [dt,dd]}));
  setPreset('all');$('preset').addEventListener('change',e=>{if(e.target.value!=='custom')setPreset(e.target.value)});
  for(const id of ['from','to'])$(id).addEventListener('change',()=>{if($('from').value>$('to').value){$('error').hidden=false;$('error').textContent='A data inicial deve ser anterior à data final.';return}$('error').hidden=true;$('preset').value='custom';render()});
  for(const id of ['type','campaign','adset','ad','metric','grain','level'])$(id).addEventListener('change',render);
  $('reset').addEventListener('click',()=>{for(const id of ['type','campaign','adset','ad'])$(id).value='';$('preset').value='all';$('error').hidden=true;setPreset('all')});
  document.querySelectorAll('[data-sort]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.sort;state.desc=state.sort===k?!state.desc:true;state.sort=k;renderTable(state.rows)}));
}catch(error){$('error').hidden=false;$('error').textContent='Não foi possível carregar os dados validados. Verifique o arquivo data.json e tente novamente. '+error.message}}
if(typeof document!=='undefined')main();
if(typeof module!=='undefined')module.exports={total,ratio,filterRows,groupRows};
