const $ = id => document.getElementById(id);
const nf = new Intl.NumberFormat('pt-BR');
const money = new Intl.NumberFormat('pt-BR', {style:'currency',currency:'BRL'});
const fmtDate = s => new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC',day:'2-digit',month:'short',year:'numeric'}).format(new Date(s+'T12:00:00Z'));
const metricNames = {spend:'Valor gasto em anúncios',impressions:'Impressões',link_clicks:'Cliques no link',landing_page_views:'Visualizações da página',conversations:'Mensagens iniciadas',profile_visits:'Visitas ao perfil',purchases:'Quantidade de compras',purchase_value:'Valor de conversão das compras',ctr:'CTR do link',cpc:'CPC do link',cpm:'CPM'};
const state = {data:null,rows:[],sort:'spend',desc:true};
function total(rows,key){let seen=false,n=0;for(const r of rows){if(r[key]!==null&&r[key]!==undefined){seen=true;n+=r[key]}}return seen?n:null}
function ratio(a,b){return a===null||b===null||b===0?null:a/b}
function number(v){return v===null?'—':nf.format(v)}
function currency(v){return v===null?'—':money.format(v/100)}
function metricTotal(rows,key){const spend=total(rows,'spend'),impressions=total(rows,'impressions'),clicks=total(rows,'link_clicks');if(key==='ctr'){const v=ratio(clicks,impressions);return v===null?null:v*100}if(key==='cpc')return ratio(spend,clicks);if(key==='cpm'){const v=ratio(spend,impressions);return v===null?null:v*1000}return total(rows,key)}
function metricValue(v,key){if(v===null)return '—';if(['spend','purchase_value','cpc','cpm'].includes(key))return currency(v);if(key==='ctr')return v.toLocaleString('pt-BR',{maximumFractionDigits:2})+'%';return number(v)}
function addOption(select,value,label){const opt=document.createElement('option');opt.value=value;opt.textContent=label;select.append(opt)}
function filterRows(rows,{from,to,c='',s='',a=''}){return rows.filter(r=>r.d>=from&&r.d<=to&&(!c||r.c===c)&&(!s||r.s===s)&&(!a||r.a===a))}
function getFiltered(){return filterRows(state.data.rows,{from:$('from').value,to:$('to').value,c:$('campaign').value,s:$('adset').value,a:$('ad').value})}
function displayName(level,code){const catalog=state.data?.catalog?.[level];if(!catalog)return code;const name=catalog[code]||code;return Object.values(catalog).filter(value=>value===name).length>1?`${name} · ${code}`:name}
function options(id,values,current,label){const el=$(id);el.replaceChildren();addOption(el,'',label);const level={campaign:'campaign',adset:'adset',ad:'ad'}[id];for(const v of values)addOption(el,v,displayName(level,v));if(values.includes(current))el.value=current;else el.value=''}
function refreshDependencies(){const c=$('campaign').value,s=$('adset').value;const inDates=state.data.rows.filter(r=>r.d>=$('from').value&&r.d<=$('to').value);const activeLabels=(list,level)=>groupRows(list,level).filter(hasActivity).sort((a,b)=>a.label.localeCompare(b.label,'pt-BR')).map(group=>group.code);
  options('campaign',activeLabels(inDates,'campaign'),c,'Todas as campanhas');
  const inCampaign=inDates.filter(r=>!$('campaign').value||r.c===$('campaign').value);
  options('adset',activeLabels(inCampaign,'adset'),s,'Todos os conjuntos');
  const inAdset=inCampaign.filter(r=>!$('adset').value||r.s===$('adset').value);
  options('ad',activeLabels(inAdset,'ad'),$('ad').value,'Todos os anúncios')}
function card(title,value,caption,primary=false){const el=document.createElement('article');el.className='kpi'+(primary?' primary':'');const t=document.createElement('span'),v=document.createElement('strong'),s=document.createElement('small');t.textContent=title;v.textContent=value;s.textContent=caption;el.append(t,v,s);return el}
function renderKpis(rows){const spend=total(rows,'spend'),clicks=total(rows,'link_clicks');const cards=[
  ['Valor gasto em anúncios',currency(spend),'Total do recorte',true],
  ['Valor de conversão das compras',currency(total(rows,'purchase_value')),'Atribuído pela Meta; não é receita recebida',true],
  ['Quantidade de compras',number(total(rows,'purchases')),'Eventos atribuídos pela Meta'],
  ['Mensagens iniciadas',number(total(rows,'conversations')),'Conversas atribuídas pela Meta'],
  ['CPC do link',metricValue(ratio(spend,clicks),'cpc'),'Gasto ÷ cliques no link'],
  ['Visitas ao perfil',number(total(rows,'profile_visits')),'Interesse no Instagram'],
  ['Visualizações da página',number(total(rows,'landing_page_views')),'Acesso ao destino'],
  ['Cliques no link',number(clicks),'Saídas do anúncio']];
  $('kpis').replaceChildren(...cards.map((c,i)=>{const el=card(...c);el.style.setProperty('--card-index',i);return el}))}
function renderDecision(rows){const spend=total(rows,'spend'),campaigns=groupRows(rows,'campaign').filter(hasActivity).sort((a,b)=>(b.spend||0)-(a.spend||0));const box=$('decision');box.replaceChildren();const label=document.createElement('span'),message=document.createElement('strong'),link=document.createElement('a');label.textContent='ONDE OLHAR AGORA';link.href='#comparacao';link.textContent='Ver campanhas ↗';if(spend&&campaigns.length>=4){const share=campaigns.slice(0,3).reduce((n,c)=>n+(c.spend||0),0)/spend*100;message.textContent=`As 3 campanhas com maior gasto concentram ${share.toLocaleString('pt-BR',{maximumFractionDigits:1})}% do investimento.`}else if(campaigns.length){message.textContent=`${campaigns[0].label} lidera o gasto no recorte: ${currency(campaigns[0].spend)}.`}else{message.textContent='Sem atividade neste recorte.';link.href='#filtros';link.textContent='Rever filtros ↗'}const copy=document.createElement('div');copy.append(label,message);const from=new Date($('from').value+'T12:00:00Z'),to=new Date($('to').value+'T12:00:00Z'),days=Math.round((to-from)/86400000)+1,prevTo=new Date(from),prevFrom=new Date(from);prevTo.setUTCDate(prevTo.getUTCDate()-1);prevFrom.setUTCDate(prevFrom.getUTCDate()-days);const date=d=>d.toISOString().slice(0,10);if(date(prevFrom)>=state.data.period.since){const previous=filterRows(state.data.rows,{from:date(prevFrom),to:date(prevTo),c:$('campaign').value,s:$('adset').value,a:$('ad').value});const context=document.createElement('small');context.textContent=`Período anterior (${fmtDate(date(prevFrom))}–${fmtDate(date(prevTo))}): ${currency(total(previous,'spend'))} investidos · ${number(total(previous,'conversations'))} conversas.`;copy.append(context)}box.append(copy,link)}
function weekStart(date){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);return d.toISOString().slice(0,10)}
function bucketFor(date,grain){return grain==='month'?date.slice(0,7):grain==='week'?weekStart(date):date}
function buildSeries(rows,key,grain,from,to){
  if(!rows.length)return [];
  const groups=new Map();for(const row of rows){const bucket=bucketFor(row.d,grain);if(!groups.has(bucket))groups.set(bucket,[]);groups.get(bucket).push(row)}
  const keys=new Set();for(let day=new Date(from+'T12:00:00Z');day<=new Date(to+'T12:00:00Z');day.setUTCDate(day.getUTCDate()+1))keys.add(bucketFor(day.toISOString().slice(0,10),grain));
  return [...keys].sort().map(bucket=>({key:bucket,value:groups.has(bucket)?metricTotal(groups.get(bucket),key):null,hasRows:groups.has(bucket)}))
}
function periodLabel(key,grain){if(grain==='month')return new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC',month:'long',year:'numeric'}).format(new Date(key+'-01T12:00:00Z'));if(grain==='week')return 'Semana de '+fmtDate(key);return fmtDate(key)}
function axisValue(value,key){const compact=new Intl.NumberFormat('pt-BR',{notation:'compact',maximumFractionDigits:1});if(key==='ctr')return value.toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';if(['cpc','cpm'].includes(key))return currency(value);return ['spend','purchase_value'].includes(key)?'R$ '+compact.format(value/100):compact.format(value)}
function chartPresentation(entries,key){const observed=entries.flatMap((entry,index)=>entry.value===null?[]:[index]);const missing=entries.length-observed.length,zeros=observed.filter(index=>entries[index].value===0).length;const sparse=entries.length>=4&&observed.length/entries.length<.35;const mode=['purchases','purchase_value'].includes(key)||sparse?'columns':['ctr','cpc','cpm'].includes(key)?'line':'area';return {mode,observed,missing,zeros}}
function niceAxisTop(highest,key){if(highest<=0)return ['purchases','conversations','profile_visits','landing_page_views','link_clicks','impressions'].includes(key)?3:1;const target=highest*1.08/3,power=10**Math.floor(Math.log10(target));const steps=[1,1.5,2,2.5,3,5,7.5,10];let tick=steps.find(step=>step*power>=target)*power;if(['purchases','conversations','profile_visits','landing_page_views','link_clicks','impressions'].includes(key))tick=Math.max(1,Math.ceil(tick));return tick*3}
function preferredGrain(key,days){if(days<=31)return 'day';if(['purchases','purchase_value'].includes(key))return 'month';if(['conversations','cpc','landing_page_views','link_clicks','ctr','cpm'].includes(key))return 'week';return 'day'}
function renderChart(rows){
  const key=$('metric').value,grain=$('grain').value;
  const entries=buildSeries(rows,key,grain,$('from').value,$('to').value);
  const presentation=chartPresentation(entries,key);
  const chart=$('chart');chart.replaceChildren();
  chart.dataset.mode=presentation.mode;
  $('chart-total').textContent=metricValue(metricTotal(rows,key),key);
  $('chart-unit').textContent=metricNames[key]+' no recorte';
  document.querySelector('.chart-legend span').textContent=presentation.mode==='columns'?'Períodos com valor registrado':metricNames[key]+' por período';
  const width=Math.max(300,Math.round(chart.getBoundingClientRect().width)),height=Math.round(chart.getBoundingClientRect().height)||280;
  const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');
  svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-hidden','true');
  const make=(tag,attrs,parent=svg)=>{const el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [name,value] of Object.entries(attrs))el.setAttribute(name,value);parent.append(el);return el};
  const top=18,bottom=height-54,left=width<500?51:70,right=width-18;
  const highest=Math.max(0,...entries.map(entry=>entry.value===null?0:entry.value));
  const max=niceAxisTop(highest,key);
  for(let i=0;i<4;i++){const y=top+(bottom-top)*i/3;const value=max*(1-i/3);make('line',{x1:left,y1:y,x2:right,y2:y,class:'chart-grid'});const label=make('text',{x:left-12,y:y+4,'text-anchor':'end',class:'chart-y-axis'});label.textContent=axisValue(value,key)}
  const points=entries.map((entry,i)=>[left+(right-left)*(entries.length===1?.5:i/(entries.length-1)),entry.value===null?null:bottom-entry.value/max*(bottom-top)]);
  if(presentation.mode==='columns'){
    const barWidth=Math.min(22,Math.max(2,(right-left)/Math.max(1,entries.length)*.78));
    for(const index of presentation.observed){const [x,y]=points[index];if(entries[index].value===0){make('circle',{cx:x,cy:bottom,r:3,class:'chart-zero'});continue}make('rect',{x:x-barWidth/2,y,width:barWidth,height:Math.max(2,bottom-y),rx:Math.min(3,barWidth/2),class:'chart-column'});make('circle',{cx:x,cy:y,r:barWidth<=5?3:4,class:'chart-column-cap'})}
  }else{
    let segment=[];const drawSegment=()=>{if(!segment.length)return;const line=segment.map(([x,y],i)=>(i?'L':'M')+x.toFixed(1)+','+y.toFixed(1)).join(' ');if(segment.length>1&&presentation.mode==='area'){const area=line+' L'+segment.at(-1)[0].toFixed(1)+','+bottom+' L'+segment[0][0].toFixed(1)+','+bottom+' Z';make('path',{d:area,class:'chart-area'})}make('path',{d:line,class:'chart-line',pathLength:1});if(segment.length===1)make('circle',{cx:segment[0][0],cy:segment[0][1],r:4,class:'chart-point'});segment=[]};
    for(const point of points){if(point[1]===null)drawSegment();else segment.push(point)}drawSegment();
    if(entries.length<=40)points.forEach(([x,y])=>{if(y!==null)make('circle',{cx:x,cy:y,r:entries.length<=15?4.5:2.5,class:'chart-point'})});
  }
  const labelCount=Math.min(width<500?4:6,entries.length);for(let i=0;i<labelCount;i++){const at=Math.round(i*(entries.length-1)/Math.max(1,labelCount-1));const x=points[at][0];const label=make('text',{x,y:height-13,'text-anchor':i===0?'start':i===labelCount-1?'end':'middle',class:'chart-axis'});const bucket=entries[at].key;label.textContent=grain==='month'?bucket.slice(5)+'/'+bucket.slice(2,4):bucket.slice(8)+'/'+bucket.slice(5,7)}
  const cursor=make('line',{x1:left,y1:top,x2:left,y2:bottom,class:'chart-cursor',visibility:'hidden'});
  const dot=make('circle',{cx:left,cy:bottom,r:6,class:'chart-cursor-point',visibility:'hidden'});
  const tip=document.createElement('div');tip.className='chart-tooltip';tip.hidden=true;tip.innerHTML='<span class="chart-tooltip-date"></span><strong class="chart-tooltip-value"></strong><small class="chart-tooltip-status"></small>';
  chart.append(svg,tip);
  if(!presentation.observed.length){const empty=document.createElement('div');empty.className='chart-empty';empty.textContent='Não há valores exportados para esta métrica neste recorte.';chart.append(empty)}
  let current=-1;const show=index=>{if(index<0||index>=entries.length||index===current)return;current=index;const entry=entries[index],[x,y]=points[index];cursor.setAttribute('x1',x);cursor.setAttribute('x2',x);cursor.setAttribute('visibility','visible');dot.setAttribute('visibility',y===null?'hidden':'visible');if(y!==null){dot.setAttribute('cx',x);dot.setAttribute('cy',y)}tip.querySelector('.chart-tooltip-date').textContent=periodLabel(entry.key,grain);tip.querySelector('.chart-tooltip-value').textContent=metricValue(entry.value,key);tip.querySelector('.chart-tooltip-status').textContent=!entry.hasRows?'Sem registro':entry.value===null?(['cpc','ctr','cpm'].includes(key)?'Sem denominador':'Sem valor exportado'):entry.value===0?'Zero registrado':metricNames[key];tip.hidden=false;tip.style.left=Math.max(65,Math.min(width-65,x))+'px'};
  const hide=()=>{current=-1;tip.hidden=true;cursor.setAttribute('visibility','hidden');dot.setAttribute('visibility','hidden')};
  const pointAt=event=>{const rect=chart.getBoundingClientRect();const x=(event.clientX-rect.left)/rect.width*width;const index=Math.max(0,Math.min(entries.length-1,Math.round((x-left)/(right-left)*(entries.length-1))));return presentation.mode==='columns'&&presentation.observed.length?presentation.observed.reduce((nearest,candidate)=>Math.abs(candidate-index)<Math.abs(nearest-index)?candidate:nearest):index};
  chart.onpointermove=event=>{if(entries.length)show(pointAt(event))};
  chart.onpointerdown=event=>{if(entries.length)show(pointAt(event))};
  chart.onpointerleave=event=>{if(event.pointerType!=='touch')hide()};
  chart.onblur=hide;
  chart.onkeydown=event=>{if(!entries.length)return;const indices=presentation.mode==='columns'?presentation.observed:entries.map((_,i)=>i);if(!indices.length)return;const position=indices.indexOf(current);const next=event.key==='ArrowRight'?indices[Math.min(indices.length-1,position+1)]:event.key==='ArrowLeft'?indices[Math.max(0,position<0?indices.length-1:position-1)]:event.key==='Home'?indices[0]:event.key==='End'?indices.at(-1):null;if(next!==null){event.preventDefault();show(next)}};
  chart.setAttribute('aria-label',metricNames[key]+' por '+(grain==='day'?'dia':grain==='week'?'semana':'mês')+'. '+(presentation.mode==='columns'?'Use as setas para percorrer períodos com valor. ':'Use as setas para explorar os valores. ')+'Total: '+metricValue(metricTotal(rows,key),key));
  const body=$('series-table');body.replaceChildren(...entries.map(entry=>{const tr=document.createElement('tr');for(const value of [periodLabel(entry.key,grain),metricValue(entry.value,key)]){const td=document.createElement('td');td.textContent=value;tr.append(td)}tr.lastChild.className='num';return tr}));
  const noRows=entries.filter(entry=>!entry.hasRows).length;
  const periods=n=>n===1?'período':'períodos';
  $('chart-note').textContent=entries.length?(presentation.observed.length?(presentation.mode==='columns'?'Colunas mostram apenas períodos com valor; passe o mouse, toque ou use as setas para encontrar cada registro.':'Passe o mouse, toque ou use as setas para ver valores exatos.'):'Nenhum valor exportado no recorte.')+(presentation.zeros?' '+presentation.zeros+' '+periods(presentation.zeros)+' com zero registrado.':'')+(presentation.missing?' '+presentation.missing+' '+periods(presentation.missing)+' sem valor para esta métrica (não são zero).':'')+(noRows?' '+noRows+' '+periods(noRows)+' sem linha no export.':'')+(grain==='week'?' Semanas nas bordas podem estar parciais.':''):'Nenhum dado no recorte.';
}
function groupRows(rows,level){const key={campaign:'c',adset:'s',ad:'a'}[level],map=new Map();for(const r of rows){if(!map.has(r[key]))map.set(r[key],[]);map.get(r[key]).push(r)}return [...map].map(([code,list])=>({code,label:displayName(level,code),spend:total(list,'spend'),impressions:total(list,'impressions'),link_clicks:total(list,'link_clicks'),landing_page_views:total(list,'landing_page_views'),conversations:total(list,'conversations'),profile_visits:total(list,'profile_visits'),purchases:total(list,'purchases'),purchase_value:total(list,'purchase_value'),cpc:ratio(total(list,'spend'),total(list,'link_clicks'))}))}
function hasActivity(group){return ['spend','impressions','link_clicks','landing_page_views','conversations','profile_visits','purchases','purchase_value'].some(key=>(group[key]||0)>0)}
const comparisonKeys=['label','spend','impressions','link_clicks','landing_page_views','conversations','profile_visits','purchases','purchase_value','cpc'];
function sortedGroups(rows,level){const all=groupRows(rows,level),groups=all.filter(hasActivity);groups.sort((a,b)=>{const av=a[state.sort],bv=b[state.sort];const cmp=typeof av==='string'?av.localeCompare(bv,'pt-BR'):((av??-1)-(bv??-1));return (state.desc?-1:1)*cmp});return {all,groups}}
function renderTable(rows){const {all,groups}=sortedGroups(rows,$('level').value);const body=$('comparison-body');body.replaceChildren(...groups.map(g=>{const tr=document.createElement('tr');for(const key of comparisonKeys){const td=document.createElement('td');td.className=key==='label'?'':'num';td.textContent=key==='label'?g.label:['spend','purchase_value','cpc'].includes(key)?currency(g[key]):number(g[key]);tr.append(td)}return tr}));document.querySelectorAll('[data-sort]').forEach(button=>{button.closest('th').setAttribute('aria-sort',state.sort===button.dataset.sort?(state.desc?'descending':'ascending'):'none')});$('table-note').textContent=groups.length?`${groups.length} ${$('level').selectedOptions[0].textContent.toLowerCase()} com atividade no recorte; ${all.length-groups.length} sem atividade ocultos. Nomes conforme o último registro de cada ID no export.`:'Nenhuma campanha, conjunto ou anúncio com atividade neste recorte. Amplie as datas ou limpe os filtros.'}
function csvCell(value){const raw=String(value??'');const safe=/^[\s]*[=+\-@]/.test(raw)?"'"+raw:raw;return '"'+safe.replaceAll('"','""')+'"'}
function exportComparison(rows,level,from,to){const {groups}=sortedGroups(rows,level);const headers=['Nome','Valor gasto em anúncios (BRL)','Impressões','Cliques no link','Visitas à página','Mensagens iniciadas','Visitas ao perfil','Quantidade de compras','Valor de conversão das compras (BRL)','CPC do link (BRL)'];const value=(group,key)=>group[key]===null?'':['spend','purchase_value','cpc'].includes(key)?(group[key]/100).toFixed(2).replace('.',','):group[key];const lines=[headers.map(csvCell).join(';'),...groups.map(g=>comparisonKeys.map(k=>csvCell(k==='label'?g.label:value(g,k))).join(';'))];return '\uFEFF'+lines.join('\r\n')+'\r\n'}
function downloadComparison(){const level=$('level').value,from=$('from').value,to=$('to').value,content=exportComparison(state.rows,level,from,to),blob=new Blob([content],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`opn-meta-${level}-${from}-${to}.csv`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function render(){refreshDependencies();const rows=getFiltered();state.rows=rows;renderKpis(rows);renderDecision(rows);renderChart(rows);renderTable(rows);$('scope').textContent=`${fmtDate($('from').value)} a ${fmtDate($('to').value)} · ${rows.length.toLocaleString('pt-BR')} linhas`;
  const active=[];for(const id of ['campaign','adset','ad'])if($(id).value)active.push($(id).selectedOptions[0].textContent);$('active').textContent=active.length?'Filtros: '+active.join(' · '):'Todas as campanhas disponíveis no período.'}
function setPreset(v){const end=state.data.period.until;let start=state.data.period.since;if(v==='30'||v==='7'){const d=new Date(end+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(Number(v)-1));start=d.toISOString().slice(0,10)}if(v==='month')start=end.slice(0,7)+'-01';$('from').value=start;$('to').value=end;render()}
async function main(){try{const response=await fetch('data.json',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);state.data=await response.json();const d=state.data;
  $('version').textContent='v '+d.build_id;$('latest').textContent=fmtDate(d.period.until);$('source-window').textContent=`Desde ${fmtDate(d.period.since)}`;
  $('from').min=$('to').min=d.period.since;$('from').max=$('to').max=d.period.until;
  $('coverage').textContent=`O arquivo diário validado contém ${nf.format(d.coverage.daily_rows)} linhas, ${d.coverage.campaigns} campanhas, ${d.coverage.adsets} conjuntos e ${d.coverage.ads} anúncios. A interface Meta mostrava ${d.coverage.ui_campaigns_observed} campanhas e ${d.coverage.ui_ads_observed} anúncios; a exportação adicional incluindo excluídas contém ${d.coverage.inventory_campaigns_exported} campanhas. A diferença cadastral segue sem reconciliação completa e não mede gasto ausente.`;
  const attributions=[...new Set(d.rows.map(r=>r.at).filter(Boolean))];
  const provenance=[['Fonte','Exportação Meta Ads, anúncio por dia'],['Última data incluída',fmtDate(d.period.until)],['Exportado em',d.source_export_time||'Horário não informado pelo arquivo'],['Importado em',new Date(d.import_time).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})],['Atribuição',`${attributions.length} configurações distintas no export; conjunto misto`],['Hash dos dados',d.data_hash]];
  $('provenance').replaceChildren(...provenance.flatMap(([k,v])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;return [dt,dd]}));
  setPreset('all');$('preset').addEventListener('change',e=>{if(e.target.value!=='custom')setPreset(e.target.value)});
  for(const id of ['from','to'])$(id).addEventListener('change',()=>{if($('from').value>$('to').value){$('error').hidden=false;$('error').textContent='A data inicial deve ser anterior à data final.';return}$('error').hidden=true;$('preset').value='custom';render()});
  for(const id of ['campaign','adset','ad','grain','level'])$(id).addEventListener('change',render);
  $('metric').addEventListener('change',()=>{const from=new Date($('from').value+'T12:00:00Z'),to=new Date($('to').value+'T12:00:00Z'),days=Math.round((to-from)/86400000)+1;$('grain').value=preferredGrain($('metric').value,days);render()});
  $('export-csv').addEventListener('click',downloadComparison);
  $('reset').addEventListener('click',()=>{for(const id of ['campaign','adset','ad'])$(id).value='';$('preset').value='all';$('error').hidden=true;setPreset('all')});
  document.querySelectorAll('[data-sort]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.sort;state.desc=state.sort===k?!state.desc:true;state.sort=k;renderTable(state.rows)}));
  window.addEventListener('resize',()=>{if(state.data)renderChart(state.rows)},{passive:true});
}catch(error){$('error').hidden=false;$('error').textContent='Não foi possível carregar os dados validados. Verifique o arquivo data.json e tente novamente. '+error.message}}
function initTheme(){const button=$('theme-toggle');if(!button)return;const apply=theme=>{document.documentElement.dataset.theme=theme;const dark=theme==='dark';button.setAttribute('aria-pressed',String(dark));button.setAttribute('aria-label',dark?'Ativar modo claro':'Ativar modo escuro');$('theme-label').textContent=dark?'Modo claro':'Modo escuro';$('theme-icon').textContent=dark?'☀':'◐';document.querySelector('meta[name="theme-color"]').content=dark?'#101a19':'#f4f5ef'};apply(document.documentElement.dataset.theme==='dark'?'dark':'light');button.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';apply(next);try{localStorage.setItem('opn-theme',next)}catch(_){}})}
function initNavigation(){const links=[...document.querySelectorAll('.nav-link')],sections=links.map(link=>document.querySelector(link.getAttribute('href'))).filter(Boolean);const select=id=>links.forEach(link=>{const active=link.getAttribute('href')==='#'+id;link.classList.toggle('current',active);if(active)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current')});let locked=false;const update=()=>{if(locked)return;if(window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-12){select(sections.at(-1).id);return}let current=sections[0];for(const section of sections){if(section.getBoundingClientRect().top<=Math.min(220,window.innerHeight*.32))current=section}select(current.id)};links.forEach(link=>link.addEventListener('click',event=>{event.preventDefault();const id=link.hash.slice(1),section=document.getElementById(id);history.pushState(null,'',link.hash);section.scrollIntoView({behavior:'instant',block:'start'});select(id);locked=true}));const unlock=event=>{if(event.type==='keydown'&&!['PageDown','PageUp','ArrowDown','ArrowUp','Home','End',' '].includes(event.key))return;if(event.type==='pointerdown'&&event.target.closest('.side-nav'))return;locked=false};for(const name of ['wheel','touchstart','pointerdown','keydown'])window.addEventListener(name,unlock,{passive:true});window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(sections.some(section=>section.id===id))select(id);else update()});window.requestAnimationFrame(()=>{if(location.hash&&sections.some(section=>section.id===location.hash.slice(1)))select(location.hash.slice(1));else update()})}
if(typeof document!=='undefined'){initTheme();initNavigation();main()}
if(typeof module!=='undefined')module.exports={total,ratio,filterRows,groupRows,hasActivity,metricTotal,buildSeries,weekStart,exportComparison,chartPresentation,niceAxisTop,preferredGrain};
