const $ = id => document.getElementById(id);
const nf = new Intl.NumberFormat('pt-BR');
const money = new Intl.NumberFormat('pt-BR', {style:'currency',currency:'BRL'});
const fmtDate = s => new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC',day:'2-digit',month:'short',year:'numeric'}).format(new Date(s+'T12:00:00Z'));
const metricNames = {spend:'Investimento',impressions:'Impressões',link_clicks:'Cliques no link',landing_page_views:'Visualizações da página',conversations:'Conversas iniciadas',profile_visits:'Visitas ao perfil',purchases:'Compras atribuídas',purchase_value:'Valor de compras atribuído',lead_motor:'Cliques no motor de reserva',lead_whats:'Cliques no WhatsApp'};
const typeNames = {'reach':'Alcance (tipo exportado)','actions:omni_landing_page_view':'Visualização da página','actions:onsite_conversion.messaging_conversation_started_7d':'Conversa por mensagem','profile_visit_view':'Visita ao perfil','actions:offsite_conversion.fb_pixel_purchase':'Compra atribuída'};
const state = {data:null,rows:[],sort:'spend',desc:true};
function total(rows,key){let seen=false,n=0;for(const r of rows){if(r[key]!==null&&r[key]!==undefined){seen=true;n+=r[key]}}return seen?n:null}
function ratio(a,b){return a===null||b===null||b===0?null:a/b}
function number(v){return v===null?'—':nf.format(v)}
function currency(v){return v===null?'—':money.format(v/100)}
function metricValue(v,key){return key==='spend'?currency(v):number(v)}
function addOption(select,value,label){const opt=document.createElement('option');opt.value=value;opt.textContent=label;select.append(opt)}
function filterRows(rows,{from,to,c='',s='',a='',t=''}){return rows.filter(r=>r.d>=from&&r.d<=to&&(!c||r.c===c)&&(!s||r.s===s)&&(!a||r.a===a)&&(!t||r.t===t))}
function getFiltered(){return filterRows(state.data.rows,{from:$('from').value,to:$('to').value,c:$('campaign').value,s:$('adset').value,a:$('ad').value,t:$('type').value})}
function options(id,values,current,label){const el=$(id);el.replaceChildren();addOption(el,'',label);for(const v of values)addOption(el,v,v);if(values.includes(current))el.value=current;else el.value=''}
function refreshDependencies(){const c=$('campaign').value,s=$('adset').value;const inDates=state.data.rows.filter(r=>r.d>=$('from').value&&r.d<=$('to').value&&(!$('type').value||r.t===$('type').value));
  const cs=[...new Set(inDates.map(r=>r.c))].sort();options('campaign',cs,c,'Todas as campanhas');
  const ss=[...new Set(inDates.filter(r=>!$('campaign').value||r.c===$('campaign').value).map(r=>r.s))].sort();options('adset',ss,s,'Todos os conjuntos');
  const aa=[...new Set(inDates.filter(r=>(!$('campaign').value||r.c===$('campaign').value)&&(!$('adset').value||r.s===$('adset').value)).map(r=>r.a))].sort();options('ad',aa,$('ad').value,'Todos os anúncios')}
function card(title,value,caption,primary=false){const el=document.createElement('article');el.className='kpi'+(primary?' primary':'');const t=document.createElement('span'),v=document.createElement('strong'),s=document.createElement('small');t.textContent=title;v.textContent=value;s.textContent=caption;el.append(t,v,s);return el}
function renderKpis(rows){const spend=total(rows,'spend'),impressions=total(rows,'impressions'),clicks=total(rows,'link_clicks'),conversations=total(rows,'conversations');const cards=[
  ['Investimento',currency(spend),'Total do recorte',true],['Impressões',number(impressions),'Exibições dos anúncios'],['Cliques no link',number(clicks),'CTR: '+(ratio(clicks,impressions)===null?'—':(ratio(clicks,impressions)*100).toLocaleString('pt-BR',{maximumFractionDigits:2})+'%')],
  ['CPC do link',ratio(spend,clicks)===null?'—':currency(ratio(spend,clicks)),'Gasto ÷ cliques'],['Conversas iniciadas',number(conversations),'Evento atribuído pela Meta'],['CPM',ratio(spend,impressions)===null?'—':currency(ratio(spend,impressions)*1000),'Gasto ÷ impressões × 1.000'],
  ['Visitas ao perfil',number(total(rows,'profile_visits')),'Instagram'],['Visualizações da página',number(total(rows,'landing_page_views')),'Página de destino'],['Compras atribuídas',number(total(rows,'purchases')),'Não confirma reservas'],['Valor de compras Meta',currency(total(rows,'purchase_value')),'Não é receita realizada'],
  ['Leads: motor de reserva',number(total(rows,'lead_motor')),'Campo ausente quando —'],['Leads: WhatsApp',number(total(rows,'lead_whats')),'Campo ausente quando —']];
  $('kpis').replaceChildren(...cards.map(c=>card(...c)))}
function renderChart(rows){const key=$('metric').value,grain=$('grain').value;const groups=new Map();for(const r of rows){const bucket=grain==='month'?r.d.slice(0,7):r.d;if(!groups.has(bucket))groups.set(bucket,[]);groups.get(bucket).push(r)}
  const entries=[...groups].sort(([a],[b])=>a.localeCompare(b)).map(([day,list])=>[day,total(list,key)]);
  const chart=$('chart');chart.replaceChildren();
  $('chart-total').textContent=metricValue(total(rows,key),key);
  $('chart-unit').textContent=metricNames[key]+' no recorte';
  const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');
  svg.setAttribute('viewBox','0 0 960 280');svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-hidden','true');
  const make=(tag,attrs,parent=svg)=>{const el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [name,value] of Object.entries(attrs))el.setAttribute(name,value);parent.append(el);return el};
  const top=20,bottom=226,left=8,right=952;
  const max=Math.max(1,...entries.map(([,v])=>v||0))*1.12;
  for(let i=0;i<4;i++){const y=top+(bottom-top)*i/3;make('line',{x1:left,y1:y,x2:right,y2:y,class:'chart-grid'});}
  if(entries.length){const points=entries.map(([,v],i)=>[left+(right-left)*(entries.length===1?.5:i/(entries.length-1)),v===null?null:bottom-v/max*(bottom-top)]);
    let segment=[];const drawSegment=()=>{if(!segment.length)return;const line=segment.map(([x,y],i)=>`${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`).join(' ');if(segment.length>1){const area=`${line} L${segment.at(-1)[0].toFixed(1)},${bottom} L${segment[0][0].toFixed(1)},${bottom} Z`;make('path',{d:area,class:'chart-area'})}make('path',{d:line,class:'chart-line',pathLength:1});segment=[]};
    for(const point of points){if(point[1]===null)drawSegment();else segment.push(point)}drawSegment();
    if(entries.length<=36)points.forEach(([x,y],i)=>{if(y===null)return;const dot=make('circle',{cx:x,cy:y,r:entries.length<=15?5:3.5,class:'chart-point'});const title=make('title',{},dot);title.textContent=`${entries[i][0]}: ${metricValue(entries[i][1],key)}`});
    const labelCount=Math.min(6,entries.length);for(let i=0;i<labelCount;i++){const at=Math.round(i*(entries.length-1)/Math.max(1,labelCount-1));const [label]=entries[at];const x=points[at][0];const text=make('text',{x,y:265,'text-anchor':i===0?'start':i===labelCount-1?'end':'middle',class:'chart-axis'});text.textContent=grain==='month'?label.slice(5)+'/'+label.slice(2,4):label.slice(8)+'/'+label.slice(5,7)}}
  chart.append(svg);chart.setAttribute('aria-label',`${metricNames[key]} em ${entries.length} ${grain==='month'?'meses':'dias'}. Total: ${metricValue(total(rows,key),key)}. Valores detalhados na tabela abaixo.`);
  const body=$('series-table');body.replaceChildren(...entries.map(([d,v])=>{const tr=document.createElement('tr');for(const value of [d,metricValue(v,key)]){const td=document.createElement('td');td.textContent=value;tr.append(td)}tr.lastChild.className='num';return tr}));
  $('chart-note').textContent=entries.length?`Há ${entries.length} ${grain==='month'?'meses':'dias'} com registros no recorte. Períodos sem linha no export não são preenchidos com zero.`:'Nenhum registro neste recorte.'}
function groupRows(rows,level){const key={campaign:'c',adset:'s',ad:'a'}[level],map=new Map();for(const r of rows){if(!map.has(r[key]))map.set(r[key],[]);map.get(r[key]).push(r)}return [...map].map(([label,list])=>({label,spend:total(list,'spend'),impressions:total(list,'impressions'),link_clicks:total(list,'link_clicks'),conversations:total(list,'conversations'),profile_visits:total(list,'profile_visits'),purchases:total(list,'purchases'),cpc:ratio(total(list,'spend'),total(list,'link_clicks'))}))}
function renderTable(rows){let groups=groupRows(rows,$('level').value);groups.sort((a,b)=>{const av=a[state.sort],bv=b[state.sort];let cmp=typeof av==='string'?av.localeCompare(bv):((av??-1)-(bv??-1));return (state.desc?-1:1)*cmp});const body=$('comparison-body');body.replaceChildren(...groups.map(g=>{const tr=document.createElement('tr');for(const key of ['label','spend','impressions','link_clicks','conversations','profile_visits','purchases','cpc']){const td=document.createElement('td');td.className=key==='label'?'':'num';td.textContent=key==='label'?g.label:key==='spend'||key==='cpc'?(g[key]===null?'—':currency(g[key])):number(g[key]);tr.append(td)}return tr}));$('table-note').textContent=groups.length?`${groups.length} entidades no recorte. Códigos preservam a identidade sem divulgar nomes internos. “—” indica campo ausente ou denominador zero.`:'Nenhuma entidade neste recorte. Amplie as datas ou limpe os filtros.'}
function render(){refreshDependencies();const rows=getFiltered();state.rows=rows;renderKpis(rows);renderChart(rows);renderTable(rows);$('scope').textContent=`${fmtDate($('from').value)} a ${fmtDate($('to').value)} · ${rows.length.toLocaleString('pt-BR')} linhas`;
  const active=[];for(const id of ['type','campaign','adset','ad'])if($(id).value)active.push($(id).selectedOptions[0].textContent);$('active').textContent=active.length?'Filtros ativos: '+active.join(' · '):'Todos os tipos e entidades disponíveis no período.'}
function setPreset(v){const end=state.data.period.until;let start=state.data.period.since;if(v==='30'||v==='7'){const d=new Date(end+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(Number(v)-1));start=d.toISOString().slice(0,10)}if(v==='month')start=end.slice(0,7)+'-01';$('from').value=start;$('to').value=end;render()}
async function main(){try{const response=await fetch('data.json',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);state.data=await response.json();const d=state.data;
  $('version').textContent='v '+d.build_id;$('latest').textContent=fmtDate(d.period.until);$('source-window').textContent=`Histórico: ${fmtDate(d.period.since)} a ${fmtDate(d.period.until)}`;
  $('from').min=$('to').min=d.period.since;$('from').max=$('to').max=d.period.until;
  const types=[...new Set(d.rows.map(r=>r.t).filter(Boolean))].sort();for(const t of types)addOption($('type'),t,typeNames[t]||`Tipo: ${t}`);
  $('coverage').textContent=`O arquivo diário validado contém ${nf.format(d.coverage.daily_rows)} linhas, ${d.coverage.campaigns} campanhas, ${d.coverage.adsets} conjuntos e ${d.coverage.ads} anúncios. A interface Meta mostrava ${d.coverage.ui_campaigns_observed} campanhas e ${d.coverage.ui_ads_observed} anúncios; a exportação adicional incluindo excluídas contém ${d.coverage.inventory_campaigns_exported} campanhas. A diferença cadastral segue sem reconciliação completa e não mede gasto ausente.`;
  const attributions=[...new Set(d.rows.map(r=>r.at).filter(Boolean))];
  const provenance=[['Fonte','Exportação Meta Ads, anúncio por dia'],['Última data incluída',fmtDate(d.period.until)],['Exportado em',d.source_export_time||'Horário não informado pelo arquivo'],['Importado em',new Date(d.import_time).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})],['Atribuição',`${attributions.length} configurações distintas no export; conjunto misto`],['Hash dos dados',d.data_hash]];
  $('provenance').replaceChildren(...provenance.flatMap(([k,v])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;return [dt,dd]}));
  setPreset('all');$('preset').addEventListener('change',e=>{if(e.target.value!=='custom')setPreset(e.target.value)});
  for(const id of ['from','to'])$(id).addEventListener('change',()=>{if($('from').value>$('to').value){$('error').hidden=false;$('error').textContent='A data inicial deve ser anterior à data final.';return}$('error').hidden=true;$('preset').value='custom';render()});
  for(const id of ['type','campaign','adset','ad','metric','grain','level'])$(id).addEventListener('change',render);
  $('reset').addEventListener('click',()=>{for(const id of ['type','campaign','adset','ad'])$(id).value='';$('preset').value='all';$('error').hidden=true;setPreset('all')});
  document.querySelectorAll('[data-sort]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.sort;state.desc=state.sort===k?!state.desc:true;state.sort=k;renderTable(state.rows)}));
}catch(error){$('error').hidden=false;$('error').textContent='Não foi possível carregar os dados validados. Verifique o arquivo data.json e tente novamente. '+error.message}}
function initTheme(){const button=$('theme-toggle');if(!button)return;const apply=theme=>{document.documentElement.dataset.theme=theme;const dark=theme==='dark';button.setAttribute('aria-pressed',String(dark));button.setAttribute('aria-label',dark?'Ativar modo claro':'Ativar modo escuro');$('theme-label').textContent=dark?'Modo claro':'Modo escuro';$('theme-icon').textContent=dark?'☀':'◐';document.querySelector('meta[name="theme-color"]').content=dark?'#101a19':'#f4f5ef'};apply(document.documentElement.dataset.theme==='dark'?'dark':'light');button.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';apply(next);try{localStorage.setItem('opn-theme',next)}catch(_){}})}
function initNavigation(){const links=[...document.querySelectorAll('.nav-link')];if(!('IntersectionObserver'in window))return;const sections=links.map(link=>document.querySelector(link.getAttribute('href'))).filter(Boolean);const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){links.forEach(link=>link.classList.toggle('current',link.getAttribute('href')==='#'+entry.target.id))}}},{rootMargin:'-18% 0px -72% 0px'});sections.forEach(section=>observer.observe(section))}
if(typeof document!=='undefined'){initTheme();initNavigation();main()}
if(typeof module!=='undefined')module.exports={total,ratio,filterRows,groupRows};
